In [1]:
# Mohammad Ali Zahir
# ID: 40077619
# COMP 333 - Lab 9

In [2]:
import pandas as pd

In [6]:
# Loading the dataset
data = pd.read_csv('./data/TheoryAssignment8-scinameUUIDs-csv.csv', encoding = "ISO-8859-1")

data.head(10)

C:\Users\Ali\AppData\Local\Temp\ipykernel_29864\3323130178.py:2: DtypeWarning: Columns (11,12,13,16,17,18,33,35) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('./data/TheoryAssignment8-scinameUUIDs-csv.csv', encoding = "ISO-8859-1")

,survey_id,recordID,mo,dy,yr,period,plot_id,plot,note1,stake,...,tag,note2,ltag,note3,prevrt,prevlet,nestdir,neststk,note4,note5
0,491ec41b-0a80-4ce9-b754-2983c6f38e71,6545,9,18,1982,62.0,4dc16022-f28d-4b9d-9062-c7bc3ad43362,13,13.0,36.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,f280bade-4e9b-447d-afe0-9e6d45e6bfb0,5220,1,24,1982,54.0,dcbbd373-c22e-46ef-ae8b-ad88f5cf7475,20,13.0,27.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2b1b4a8a-c3e9-4781-a5f9-18b081383876,18932,8,7,1991,162.0,1e87b11b-4795-4f41-bdff-2d5c4412be25,19,13.0,33.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D
3,e98e66c4-514b-45f7-9d95-336c05a72b21,20588,1,24,1993,179.0,91829d58-c12e-47e8-ae31-185f46be21d2,12,13.0,41.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,768cdd0d-93bc-4c74-9dcd-d1ed48b7501e,7020,11,21,1982,63.0,f24f2db6-eadd-4de9-9d2f-95aea376c013,24,13.0,72.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,13851c71-013d-4989-bd49-7d7a65af7709,7645,4,16,1983,67.0,f24f2db6-eadd-4de9-9d2f-95aea376c013,24,13.0,21.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,c10df07b-ca12-450f-8240-94e146dea1d1,8641,11,13,1983,74.0,6a090985-a7ce-4c04-b146-9b401d1dd796,15,13.0,25.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1bd57490-6747-4949-8f98-ad6faced7341,9495,8,26,1984,82.0,aab65971-f64b-425e-9a78-17d7ec63423c,9,13.0,21.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,723e792b-9f69-4d7a-84c6-d1c1ee66ea63,9583,9,30,1984,83.0,6a090985-a7ce-4c04-b146-9b401d1dd796,15,13.0,37.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,b7202dd9-332a-41f0-a975-56c55f803164,9862,1,20,1985,86.0,4dc16022-f28d-4b9d-9062-c7bc3ad43362,13,13.0,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
def define_season(row):
    if 'united states' in row['country'].lower() and (row['mo'] == 12 and row['mo'] < 3): 
        return 'winter'
    elif 'united states' in row['country'].lower() and (row['mo'] >= 3 and row['mo'] < 6):
        return 'spring'
    elif 'united states' in row['country'].lower() and (row['mo'] >= 6 and row['mo'] < 9):
        return 'summer'
    elif 'united states' in row['country'].lower() and (row['mo'] >= 9 and row['mo'] < 12):
        return 'fall'
    elif 'australia' in row['country'].lower() and (row['mo'] >= 6 and row['mo'] < 9):
        return 'winter'
    elif 'australia' in row['country'].lower() and (row['mo'] >= 9 and row['mo'] < 12):
        return 'spring'
    elif 'australia' in row['country'].lower() and (row['mo'] == 12 and row['mo'] < 3):
        return 'summer'
    elif 'australia' in row['country'].lower() and (row['mo'] >= 3 and row['mo'] < 6):
        return 'fall'
    else:
        return 'summer'
        
data['seasons'] = data.apply(lambda row: define_season(row), axis=1)

AttributeError: 'float' object has no attribute 'lower'